#okhttp连接池配置
okhttp:
  read-timeout: 1000
  write-timeout: 1000
  connection-timeout: 1000
  max-idle-connections: 30
  keep-alive-duration: 10   #单位分

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:  #开启熔断
    enabled: true


